version: "3.8"
services:
   web_server:
      user: "root"
      image: httpd:alpine
      restart: always
      ports:
              - 1501:80
      volumes:
         - ./var/www/html:/usr/local/apache2/htdocs
