# 기반 이미지를 우분투로 선택
FROM ubuntu:20.04

# 패키지 목록을 업데이트
RUN apt-get -y update && apt-get install 
# RUN apt-get -y --no-install-recommends install wget git ssh

# imagemagick 설치
RUN apt install -y imagemagick wget git ssh